[server]
maxUploadSize = 200
enableXsrfProtection = false
maxMessageSize = 200

[browser]
gatherUsageStats = false

[logger]
level = "info"

[runner]
magicEnabled = true
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "minimal"

[memory]
ttl = 3600 